language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"

env: TWITTELECT_DB_SERVER=localhost TWITTELECT_DB_NAME=twittelect TWITTELECT_DB_USER=travis TWITTELECT_DB_PASS=''

before_script:
  - mysql -e 'create database twittelect;'
  - mysql -D twittelect < db/twittelect.sql

install:
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest --installdeps .

script:
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
  - cover

after_success:
  - cover -report coveralls

